Fix/#0 db version up
ChaSaji/PickNic pull request #136
Opened 2024-06-03 06:09 UTC by githubeWYrd4nG

2024-06-18 09:28 UTC, endo1322 requested changes
DB初期化後の再リロードをするとエラーが吐かれます。
詳しい手順は以下です。
確認お願いします。

### 初期化
1. native app 起動
2. DBスクリーンで`Drop Table`実行
3. terminal上でr（リロード）指定
### 確認して欲しいこと
4. Cookingなどに移動→テーブルが初期化されレコードの情報が確認できる
5. terminal上でr（リロード）指定
6. Cookingなどに移動→`Property 'InsertItem' doesn't exist` とエラーが吐かれる。また、DBスクリーンでSeeAllItemしても同じえらが吐かれる。

2024-06-19 05:53 UTC, githubeWYrd4nG reviewed
一応更新を確認しました。
多分動きます。

2024-06-20 12:12 UTC, Konata-mi approved these changes
食材の消費を確認

2024-06-21 08:53 UTC, endo1322 approved these changes
LGTM！
ありがとう助かりました泣

2024-06-21 09:15 UTC, Ilekaede reviewed
nice!

2024-06-21 09:17 UTC, Ilekaede approved these changes

2024-06-21 09:17 UTC, merged