Feature/#139 event list
ChaSaji/PickNic pull request #163
Opened 2024-06-08 11:25 UTC by karin26801684

### やったこと
-イベント一覧の画面を作成しました。

### 確認事項
- `npm run build`が通る
- `http://localhost:3000/events`にて、デザイン通り実装ができていることの確認

2024-06-08 15:55 UTC, endo1322 requested changes
修正お願いします！

2024-06-08 15:55 UTC, endo1322 commented on web/src/app/(app)/events/page.tsx
> +export default function App() {
`App()`をEventListPage()とかEventsPage()とかに直しておいてください。

2024-06-08 15:55 UTC, endo1322 commented on web/src/app/(app)/events/page.tsx
> +export default function App() {
命名に意味はそんなにないですが、なんとなくで。

2024-06-08 15:55 UTC, endo1322 commented on web/src/app/(app)/events/page.tsx
> +    // <Tittle />
この辺のコメントアウト消しといてー

2024-06-08 15:55 UTC, endo1322 commented on web/src/app/(app)/events/styles.css
> +  }
全部のdivに適応されてしまうので、必要な部分にだけ適用させてください。

2024-06-08 15:55 UTC, endo1322 commented on web/src/app/(app)/events/styles.css
> +  }
``` typescript
<table style={{
  textAlign: 'center',
  width: '100%',
  borderSpacing: 0,
  tableLayout: 'fixed',
  border: 'solid 1px #000'
}} {...getTableProps()}>
  {/* テーブルの内容 */}
</table>
```
上記のような形式で直接JSX内にstyle書けるので、今回そっちの書き方で行きたいです。
`border-spacing`は`borderSpacing`みたいにキャメルケースで書くことになります。

2024-06-08 15:55 UTC, endo1322 commented on web/src/app/(app)/events/tableData.ts
この内容自体、`web/src/app/(app)/events/create/page.tsx`の`export default function App() {`の上あたりに書いちゃってください。

2024-06-20 11:56 UTC, githubeWYrd4nG approved these changes

2024-06-26 06:27 UTC, endo1322 approved these changes
LGTM!

2024-06-26 06:27 UTC, merged