UPDATE, DELETEの処理を作成
ChaSaji/PickNic pull request #173
Opened 2024-06-20 01:33 UTC by Ilekaede

closed #172 

## やったこと
- イベント作成のUPDATE, DELETEメソッドに対する処理を作成した
- 

## 確認事項
- サーバを立ち上げた状態で http://localhost:8000/docs# を開き,　PUTでAPIを実行した時に同じものがレスポンスとして帰ってくるか確認
- 自分はrequest bodyを以下のようにしました．
{
    "event_name": "イベント1",
    "organizer": "主催者",
    "term": "2024-05-10",
    "overview": "概要の説明",
    "badge_img": "ieyasu",
    "target_img": "hamamatsu_castle_img",
    "target_name": "hamamatsu_castle_name",
    "position": [12.345, 3456.777]
}

- event_idは好きな数字でも入れてください
- DELETEはレスポンスが返ってきてることを確認すればOK，NULLが返ってくるはずです．

2024-06-24 05:34 UTC, githubeWYrd4nG approved these changes
確認事項は満たしている

2024-06-26 05:38 UTC, endo1322 requested changes

2024-06-26 05:38 UTC, endo1322 commented on api/api/routers/event.py
> +    return event_schema.EventCreateResponse(**event_data)
PUTメソッドのリクエストボディについて、変更が必要な箇所だけ指定するようにしたいから、`event_schema.EventCreateResponse`について要素をoptionalで指定した`EventUpdate`（例）を別途作成して指定した方がいいかなと思います。
現状、リクエストの要素がかけてるとエラーレスポンスになるので。

2024-06-26 05:38 UTC, endo1322 commented on api/api/routers/event.py
> +    return # NULLを返す
NULLを返すのは良くないので、やっぱ削除したデータを返すなどするといいかと思いました。

2024-06-30 07:45 UTC, endo1322 requested changes
修正お願いします。

2024-06-30 07:45 UTC, endo1322 commented on api/api/routers/event.py
> +    return event_schema.EventCreateResponse(**event_data)
return の形式が`event_schema.EventCreateResponse()`になっているので修正してください

2024-06-30 07:45 UTC, endo1322 commented on api/api/routers/event.py
> +    return event_schema.EventDetail(id=event_id, event_name="イベント1", organizer="主催者", start_date="2024-05-10T00:00:00", end_date="2025-03-22T00:00:00", overview="概要の説明", badge_img="ieyasu", target_im
修正レビューではないですが、
現状responseについて、
- GET
  - Event, EventDetailなどオブジェクト
- POST
  - EventCreateResponseのようなPOSTメソッド専用のレスポンススキーマ
- PUT
  - EventUpdateResponseのようなPUTメソッド専用のレスポンススキーマ
- DELETE
  - Event, EventDetailなどオブジェクト

になってますが、特にDELETEについて問題ないですか？
同様にEventDeleteResponseを作ってもいいかなと思いました。

2024-06-30 07:45 UTC, endo1322 commented on api/api/routers/event.py
> +    return event_schema.EventDetail(id=event_id, event_name="イベント1", organizer="主催者", start_date="2024-05-10T00:00:00", end_date="2025-03-22T00:00:00", overview="概要の説明", badge_img="ieyasu", target_im
おそらく命名や形式については今後も以上の形式をベースに開発が進行すると思います。

2024-06-30 07:45 UTC, endo1322 commented on api/api/routers/event.py
ついでに8行目について完全に見落としてましたが、レスポンスがEventBaseのListになっているので、`event_schema.EventBase`に修正してください。
`event_schema.EventBase`はリクエスト・レスポンススキーマを作るベースなので実際にリクエスト・レスポンススキーマに指定することは推奨しないです。あとidも持ってないです。

2024-07-01 06:09 UTC, Ilekaede commented on api/api/routers/event.py
> +    return event_schema.EventDetail(id=event_id, event_name="イベント1", organizer="主催者", start_date="2024-05-10T00:00:00", end_date="2025-03-22T00:00:00", overview="概要の説明", badge_img="ieyasu", target_im
つくる

2024-07-01 11:38 UTC, endo1322 approved these changes
LGTM

2024-07-01 11:38 UTC, merged