入力フォームを作成したよ
ChaSaji/PickNic pull request #177
Opened 2024-06-20 11:16 UTC by Konata-mi

close #138 

### やったこと
- 入力フォームページの実装 cd12467787f13880b0165b306e0e464d0f2bb45e

### 確認事項
- `npm run dev`で実行できることの確認
- `npm run build`, `npm run start`で実行できることの確認
- `http://localhost:XXXX/events/create`で入力フォームが開けるかどうか
- UIが使用通り実装されていることの確認
- 各入力フォームのエラーが出力されるかどうか
- 登録ボタンでコンソールに情報がでるかどうか

2024-06-20 11:49 UTC, githubeWYrd4nG requested changes
パスが競合しとる
それを治せば動く

2024-06-20 11:57 UTC, githubeWYrd4nG approved these changes
動いとる

2024-06-24 01:38 UTC, Ilekaede reviewed
npm run devしたら404出とる

2024-06-24 03:35 UTC, Ilekaede submitted a review, later dismissed

2024-06-30 08:37 UTC, endo1322 requested changes
全体を通して、使用してない変数などは特別な理由がない限り削除してください。
コンソールの出力も`onSubmit`のもの以外は削除してしまってください。

2024-06-30 08:37 UTC, endo1322 commented on web/src/schemas/inputSchema.ts
> +    .regex(/^[0-9]+$/,{ message: "入力は半角の数字のみです", }),
緯度経度の最小・最大の範囲はバリデーションをかけるようにしてもいいのかなって思いました。
ただ、今後マップから地点指定してみたいにするなど予定があるなら対応不要かと思います。

2024-06-30 08:37 UTC, endo1322 commented on web/src/app/(app)/events/create/page.tsx
> +  }
どこでも使ってないんで消してください。

2024-06-30 08:37 UTC, endo1322 commented on web/src/app/(app)/events/create/page.tsx
> +}
これも使ってないんで消してください。

2024-06-30 08:37 UTC, endo1322 commented on web/src/app/(app)/events/create/page.tsx
> +              />
ちなみ`type="number"`を渡すことで、プリミティブの`<input />`にtype="number"`を渡せるように書いているので、そうすると数値のみしか入力できないようにできます。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input

2024-06-30 08:37 UTC, endo1322 commented on web/src/app/(app)/events/create/page.tsx
> +          </div>
コンポーネント化しない理由はありますか？

2024-06-30 08:37 UTC, endo1322 commented on web/src/schemas/inputSchema.ts
ファイル名が`inputSchema`だと抽象的すぎるので、ファイル名スキーマ名ともに`eventSchema`などとするとわかりやすいかと思います。

2024-06-30 08:37 UTC, endo1322 commented on web/src/app/(app)/events/create/page.tsx
> +          </div>
これも緯度経度はセットなのでそれ用のコンポーネントを作ってもいいのかなと思いました。
少し意見が分かれますが、メリットとしては、page.tsxにおいて全て抽象的なコンポーネントで記述できるため、コードが簡素的になることと、編集ページでも同様の記述をしそうなので再利用性が高まるところにあるかと思います。
デメリットとしては、少しコンポーネントが特化しすぎたものになることかと思います。ただ、今回の開発では再利用の余地があるのでそこまで気にしなくていいかなと思いました。

2024-07-13 11:23 UTC, endo1322 approved these changes
lgtm!

2024-07-13 11:23 UTC, merged