auth-test
ChaSaji/PickNic pull request #184
Opened 2024-06-26 05:06 UTC by githubeWYrd4nG

実行手順
1.PickNic\api\api\libに移動
2.uvicorn auth.main:app --reloadを実行
3./*生成されたURL*//docs#を開く
4.POST/users/でユーザ登録
5.Post/token/でUsername,passwordを用いてログイン
6.Get/users/meでログインユーザを確認

以下のようにしてユーザ認証が必要な機能ページの作成をする。
# 認証が必要なエンドポイントの追加方法
@app.get("/protected")
async def read_protected(current_user: User = Depends(get_current_user)):
    return {"message": "This is a protected endpoint", "user": current_user}

2024-06-26 05:28 UTC, githubeWYrd4nG commented
追加で
7.POST/logoutでログアウトを確認
8.Get/users/meで返答が以下のようになっていることを確認
```
Response body
Download
{
  "detail": "Not authenticated"
}

```

2024-06-26 07:34 UTC, githubeWYrd4nG commented
実行手順
1.PickNic\api\api\libに移動
2.uvicorn auth.main:app --reloadを実行
3./生成されたURL//docs#を開く
4.POST/users/でユーザ登録
**5.画面右上のAuthorizeからログイン**
6.Get/users/meでログインユーザを確認
7.PUT/users_update/{user_id}からユーザ情報変更
8.再度ログイン
9.ユーザ削除
10.POST/loginでアクセストークンが更新されることの確認

実際にログインする場合は、URLに
`'Authorization: Bearer "アクセストークン"を用いる`

以下のようにしてユーザ認証が必要な機能ページの作成をする。

2024-06-30 09:23 UTC, endo1322 requested changes
説明が足りてなく申し訳なかったですが、`lib/auth`に記述して欲しかったのはあくまでauth処理に必要なヘルパー関数のようなものです。
request, response schema定義、router定義、db schema(model)定義、crud操作についてはそれぞれそれ用のディレクトリを切っているので、その下で書くようにしてください。
それでfastapiのインスタンスについても、apiアプリ全体のインスタンスをrootのmain.pyで切っているのでそれに載せるようにしてください。
下記記事を参考に進めているので目を通しておいてください。
https://zenn.dev/sh0nk/books/537bb028709ab9/viewer/f1b6fc

加えて必要なライブラリに関しては、今回パッケージマネージャに`poetry`を使用しているので、それを通してインストールしてください。（インストールしたライブラリが`pyproject.toml`に、依存ライブラリがバージョン付きで`poetry.lock`に記述されます。）

また適宜、さくらい君とも連携を取りながら進めてもらえるといいかと思います。



確認事項にあった処理については問題なく動作確認できました。

2024-07-01 06:43 UTC, githubeWYrd4nG commented
実行手順
`PickNick/api`に移動
`poetry run uvicorn api.main:app --reload`で起動
試験内容
3./生成されたURL//docs#を開く
4.POST/users/でユーザ登録
5.画面右上のAuthorizeからログイン
6.Get/users/meでログインユーザを確認
7.PUT/users_update/{user_id}からユーザ情報変更
8.再度ログイン
9.ユーザ削除
10.POST/loginでアクセストークンが更新されることの確認

2024-07-01 10:45 UTC, endo1322 reviewed
`.env`に下記を記載して！

DATABASE_URL="sqlite:///test.db"

2024-07-01 11:09 UTC, Konata-mi submitted a review, later dismissed
LGTM dayo

2024-07-01 11:46 UTC, endo1322 approved these changes
LGTM！

2024-07-01 11:46 UTC, merged