モバイルから画像をアップロードしてクラウド上に保存し，パスをDB上に格納するした
ChaSaji/PickNic pull request #242
Opened 2024-07-19 07:06 UTC by Ilekaede

#233 closed.

## やったこと
- routers/mobile/events/{event_id}/uploadfileでアップロードされた画像をR2にアップロードするようにしました．
- R2上のパスをDB内のPhoto.pass2photoに格納する処理を追加しました．

## 確認事項
- R2にアップロードが適切に行える．
- パスがDBに格納されている．

## チェックでの注意事項
- .envにAWSのアクセスキー，シークレットアクセスキー，エンドポイントURL，バケットネームを追加してください(詳細はSlack)

2024-07-19 07:09 UTC, endo1322 requested changes
取り急ぎ、最新のdevelopのmergeをお願いします。

2024-07-19 08:41 UTC, endo1322 requested changes
また取り急ぎだけど、`x-user-id`はstringで受け取れるようにしてください。
http://localhost:8000/docs#/default/register_user_mobile_create_user__post で確認できますが、作られるMoblie UserのIDは以下のような形式です。
```
{
  "id": "$2b$12$kixj3v/vGr6hFiCT0IhnBOYps4lO6vMjAtTK1C06iCO6vjlGLwsi6",
  "name": "string"
}
```

2024-07-20 10:39 UTC, Ilekaede commented
- pass2photoのphoto_idってEventのFKであるphoto_idと同じでOKだっけ．．．？

2024-07-20 17:05 UTC, endo1322 approved these changes
lgtm !

2024-07-20 17:05 UTC, merged